#ifndef INCLUDE_CSTRIKE_H
#define INCLUDE_CSTRIKE_H

enum
{
	TEAM_UNASSIGNED = 0,
	TEAM_TERRORIST,
	TEAM_CT,
	TEAM_SPECTATOR = 6,
};

enum
{
	MESSAGE_VOICEMASK = 64,
	MESSAGE_REQSTATE,
	MESSAGE_CURWEAPON,
	MESSAGE_GEIGER,
	MESSAGE_FLASHLIGHT,
	MESSAGE_FLASHBAT,
	MESSAGE_HEALTH,
	MESSAGE_DAMAGE,
	MESSAGE_BATTERY,
	MESSAGE_TRAIN,
	MESSAGE_HUDTEXTPRO,
	MESSAGE_HUDTEXT,
	MESSAGE_SAYTEXT,
	MESSAGE_TEXTMSG,
	MESSAGE_WEAPONLIST,
	MESSAGE_RESETHUD,
	MESSAGE_INITHUD,
	MESSAGE_VIEWMODE,
	MESSAGE_GAMETITLE,
	MESSAGE_DEATHMSG,
	MESSAGE_SCOREATTRIB,
	MESSAGE_SCOREINFO,
	MESSAGE_TEAMINFO,
	MESSAGE_TEAMSCORE,
	MESSAGE_GAMEMODE,
	MESSAGE_MOTD,
	MESSAGE_SERVERNAME,
	MESSAGE_AMMOPICKUP,
	MESSAGE_WEAPPICKUP,
	MESSAGE_ITEMPICKUP,
	MESSAGE_HIDEWEAPON,
	MESSAGE_SETFOV,
	MESSAGE_SHOWMENU,
	MESSAGE_SCREENSHAKE,
	MESSAGE_SCREENFADE,
	MESSAGE_AMMOX,
	MESSAGE_SENDAUDIO,
	MESSAGE_ROUNDTIME,
	MESSAGE_MONEY,
	MESSAGE_ARMORTYPE,
	MESSAGE_BLINKACCT,
	MESSAGE_STATUSVALUE,
	MESSAGE_STATUSTEXT,
	MESSAGE_STATUSICON,
	MESSAGE_BARTIME,
	MESSAGE_RELOADSOUND,
	MESSAGE_CROSSHAIR,
	MESSAGE_NVGTOGGLE,
	MESSAGE_RADAR,
	MESSAGE_SPECTATOR,
	MESSAGE_VGUIMENU,
	MESSAGE_TUTORTEXT,
	MESSAGE_TUTORLINE,
	MESSAGE_TUTORSTATE,
	MESSAGE_TUTORCLOSE,
	MESSAGE_ALLOWSPEC,
	MESSAGE_BOMBDROP,
	MESSAGE_BOMBPICKUP,
	MESSAGE_CLCORPSE,
	MESSAGE_HOSTAGEPOS,
	MESSAGE_HOSTAGEK,
	MESSAGE_HLTV,
	MESSAGE_SPECHEALTH,
	MESSAGE_FORCECAM,
	MESSAGE_ADSTOP,
	MESSAGE_RECEIVEW,
	MESSAGE_CZCAREER,
	MESSAGE_CZCAREERHUD,
	MESSAGE_SHADOWIDX,
	MESSAGE_TASKTIME,
	MESSAGE_SCENARIO,
	MESSAGE_BOTVOICE,
	MESSAGE_BUYCLOSE,
	MESSAGE_SPECHEALTH2,
	MESSAGE_BARTIME2,
	MESSAGE_ITEMSTATUS,
	MESSAGE_LOCATION,
	MESSAGE_BOTPROGRESS,
	MESSAGE_BRASS,
	MESSAGE_FOG,
	MESSAGE_SHOWTIMER,
	MESSAGE_HUDTEXTARGS,
};

enum
{
	EO_Spawn = 0,
	EO_Precache,
	EO_Restart,
	EO_KeyValue,
	EO_Save,
	EO_Restore,
	EO_ObjectCaps,
	EO_Activate,
	EO_SetObjectCollisionBox,
	EO_Classify,
	EO_DeathNotice,
	EO_TraceAttack,
	EO_TakeDamage,
	EO_TakeHealth,
	EO_Killed,
	EO_BloodColor,
	EO_TraceBleed,
	EO_IsTriggered,
	EO_MyMonsterPointer,
	EO_MySquadMonsterPointer,
	EO_GetToggleState,
	EO_AddPoints,
	EO_AddPointsToTeam,
	EO_AddPlayerItem,
	EO_RemovePlayerItem,
	EO_GiveAmmo,
	EO_GetDelay,
	EO_IsMoving,
	EO_OverrideReset,
	EO_DamageDealt,
	EO_SetToggleState,
	EO_OnCreate,
	EO_OnDestroy,
	EO_OnControls,
	EO_IsSneaking,
	EO_IsAlive,
	EO_IsBSPModel,
	EO_ReflectGauss,
	EO_HasTarget,
	EO_IsInWorld,
	EO_IsPlayer,
	EO_IsNetClient,
	EO_TeamID,
	EO_GetNextTarget,
	EO_Think,
	EO_Touch,
	EO_Use,
	EO_Blocked,
	EO_Respawn,
	EO_UpdateOwner,
	EO_FBecomeProne,
	EO_Center,
	EO_EyePosition,
	EO_EarPosition,
	EO_BodyTarget,
	EO_Illumination,
	EO_FVisibleCBase,
	EO_FVisibleVec,

	EO_Animating_HandleAnimEvent,

	EO_Item_AddToPlayer = 59,
	EO_Item_AddDuplicate,
	EO_Item_GetItemInfo,
	EO_Item_CanDeploy,
	EO_Item_CanDrop,
	EO_Item_Deploy,
	EO_Item_IsWeapon,
	EO_Item_CanHolster,
	EO_Item_Holster,
	EO_Item_UpdateItemInfo,
	EO_Item_ItemPreFrame,
	EO_Item_ItemPostFrame,
	EO_Item_Drop,
	EO_Item_Kill,
	EO_Item_AttachToPlayer,
	EO_Item_PrimaryAmmoIndex,
	EO_Item_SecondaryAmmoIndex,
	EO_Item_UpdateClientData,
	EO_Item_GetWeaponPtr,
	EO_Item_GetMaxSpeed,
	EO_Item_ItemSlot,

	EO_Weapon_ExtractAmmo,
	EO_Weapon_ExtractClipAmmo,
	EO_Weapon_AddWeapon,
	EO_Weapon_PlayEmptySound,
	EO_Weapon_ResetEmptySound,
	EO_Weapon_SendWeaponAnim,
	EO_Weapon_IsUseable,
	EO_Weapon_PrimaryAttack,
	EO_Weapon_SecondaryAttack,
	EO_Weapon_Reload,
	EO_Weapon_WeaponIdle,
	EO_Weapon_RetireWeapon,
	EO_Weapon_ShouldWeaponIdle,
	EO_Weapon_UseDecrement,

	EO_Monster_ChangeYaw = 59,
	EO_Monster_HasHumanGibs,
	EO_Monster_HasAlienGibs,
	EO_Monster_FadeMonter,
	EO_Monster_GibMonster,
	EO_Monster_GetDeathActivity,
	EO_Monster_BecomeDeaed,
	EO_Monster_ShouldFadeOnDeath,
	EO_Monster_IRelationship,
	EO_Monster_PainSound,
	EO_Monster_ResetMaxSpeed,
	EO_Monster_ReportAIState,
	EO_Monster_MonsterInitDead,
	EO_Monster_Look,
	EO_Monster_BestVisibleEnemy,
	EO_Monster_FInViewConeCBase,
	EO_Monster_FInViewConeVec,

	EO_Player_Jump,
	EO_Player_Duck,
	EO_Player_PreThink,
	EO_Player_PostThink,
	EO_Player_GetGunPosition,
	EO_Player_IsBot,
	EO_Player_UpdateClientData,
	EO_Player_ImpulseCommands,
	EO_Player_RoundRespawn,
	EO_Player_GetAutoaimVector,
	EO_Player_Blind,
	EO_Player_OnTouchingWeapon,
};

enum
{
	CSW_P228 = 1,
	CSW_SHIELD,
	CSW_SCOUT,
	CSW_HEGRENADE,
	CSW_XM1014,
	CSW_C4,
	CSW_MAC10,
	CSW_AUG,
	CSW_SMOKEGRENADE,
	CSW_ELITE,
	CSW_FIVESEVEN,
	CSW_UMP45,
	CSW_SG550,
	CSW_GALIL,
	CSW_FAMAS,
	CSW_USP,
	CSW_GLOCK18,
	CSW_AWP,
	CSW_MP5NAVY,
	CSW_M249,
	CSW_M3,
	CSW_M4A1,
	CSW_TMP,
	CSW_G3SG1,
	CSW_FLASHBANG,
	CSW_DEAGLE,
	CSW_SG552,
	CSW_AK47,
	CSW_KNIFE,
	CSW_P90,
	CSW_VEST,
	CSW_VESTHELM,
};


enum
{
	CBaseEntity_EntVars,
	CBaseEntity_GoalEnt = 4,
	CBaseEntity_Link = 8,
	CBaseEntity_Think = 12,
	CBaseEntity_Touch = 16,
	CBaseEntity_Use = 20,
	CBaseEntity_Blocked = 24,
	CBaseEntity_CurrentAmmoPtr = 28,
	CBaseEntity_Entity = 28,
	CBaseEntity_CurrentAmmo = 32,
	CBaseEntity_MaxAmmoBuckshot = 36,
	CBaseEntity_AmmoBuckshot = 40,
	CBaseEntity_MaxAmmo9MM = 44,
	CBaseEntity_Ammo9MM = 48,
	CBaseEntity_MaxAmmo556Nato = 52,
	CBaseEntity_Ammo556Nato = 56,
	CBaseEntity_MaxAmmo556NatoBox = 60,
	CBaseEntity_Ammo556NatoBox = 64,
	CBaseEntity_MaxAmmo762Nato = 68,
	CBaseEntity_Ammo762Nato = 72,
	CBaseEntity_MaxAmmo45ACP = 76,
	CBaseEntity_Ammo45ACP = 80,
	CBaseEntity_MaxAmmo50AE = 84,
	CBaseEntity_Ammo50AE = 88,
	CBaseEntity_MaxAmmo338MAG = 92,
	CBaseEntity_Ammo338MAG = 96,
	CBaseEntity_MaxAmmo57MM = 100,
	CBaseEntity_Ammo57MM = 104,
	CBaseEntity_MaxAmmo357SIG = 108,
	CBaseEntity_Ammo357SIG = 112,
	CBaseEntity_StartThrow = 116,
	CBaseEntity_ReleaseThrow = 120,
	CBaseEntity_Swing = 124,
	CBaseEntity_HasDisconnected = 128,

	CBaseDelay_Delay = 136,
	CBaseDelay_IsKillTarget = 140,

	CBaseAnimating_FrameRate = 144,
	CBaseAnimating_GroundSpeed = 148,
	CBaseAnimating_LastEventCheck = 152,
	CBaseAnimating_SequenceFinished = 156,
	CBaseAnimating_SequenceLoops = 160,

	CBaseToggle_ToggleState = 164,
	CBaseToggle_ActivateFinished = 168,
	CBaseToggle_MoveDistance = 172,
	CBaseToggle_Wait = 176,
	CBaseToggle_Lip = 180,
	CBaseToggle_TWidth = 184,
	CBaseToggle_TLength = 188,
	CBaseToggle_Position1X = 192,
	CBaseToggle_Position1Y = 196,
	CBaseToggle_Position1Z = 200,
	CBaseToggle_Position2X = 204,
	CBaseToggle_Position2Y = 208,
	CBaseToggle_Position2Z = 212,
	CBaseToggle_Angle1X = 216,
	CBaseToggle_Angle1Y = 220,
	CBaseToggle_Angle1Z = 224,
	CBaseToggle_Angle2X = 228,
	CBaseToggle_Angle2Y = 232,
	CBaseToggle_Angle2Z = 236,
	CBaseToggle_TriggersLeft = 240,
	CBaseToggle_Height = 244,
	CBaseToggle_ActivatorEnt = 248,
	CBaseToggle_ActivatorSerialNumber = 252,
	CBaseToggle_CallWhenMoveDone = 256,
	CBaseToggle_FinalDestX = 260,
	CBaseToggle_FinalDestY = 264,
	CBaseToggle_FinalDestZ = 268,
	CBaseToggle_FinalAngleX = 272,
	CBaseToggle_FinalAngleY = 276,
	CBaseToggle_FinalAngleZ = 280,
	CBaseToggle_DamageInflictBits = 284,
	CBaseToggle_Master = 288,

	CBaseMonster_Activity = 292,
	CBaseMonster_IdealActivity = 296,
	CBaseMonster_LastHitGroup = 300,
	CBaseMonster_DamageTypeBits = 304,
	CBaseMonster_TimeBasedDamage = 308,
	CBaseMonster_MonsterState = 316,
	CBaseMonster_IdealMonsterState = 320,
	CBaseMonster_Conditions = 324,
	CBaseMonster_Memory = 328,
	CBaseMonster_NextAttack = 332,
	CBaseMonster_EnemyEnt = 336,
	CBaseMonster_EnemySerialNumber = 340,
	CBaseMonster_TargetEnt = 344,
	CBaseMonster_TargetSerialNumber = 348,
	CBaseMonster_FieldOfView = 352,
	CBaseMonster_BloodColor = 356,
	CBaseMonster_HackedGunPosX = 360,
	CBaseMonster_HackedGunPosY = 364,
	CBaseMonster_HackedGunPosZ = 368,
	CBaseMonster_EnemyLKPX = 372,
	CBaseMonster_EnemyLKPY = 376,
	CBaseMonster_EnemyLKPZ = 380,

	CBasePlayer_RandomSeed = 384,
	CBasePlayer_PlayerBleed = 388,
	CBasePlayer_ObserverTargetEnt = 392,
	CBasePlayer_ObserverTargetSerialNumber = 396,
	CBasePlayer_NextObserverInput = 400,
	CBasePlayer_ObserverWeapon = 404,
	CBasePlayer_ObserverC4State = 408,
	CBasePlayer_ObserverHasDefuser = 412,
	CBasePlayer_ObserverLastMode = 416,
	CBasePlayer_FlinchTime = 420,
	CBasePlayer_AnimTime = 424,
	CBasePlayer_HighDamage = 428,
	CBasePlayer_VelocityModifierX = 432,
	CBasePlayer_LastZoom = 436,
	CBasePlayer_ResumeZoom = 440,
	CBasePlayer_EjectBrass = 444,
	CBasePlayer_Kevlar = 448,
	CBasePlayer_NotKilled = 452,
	CBasePlayer_Team = 456,
	CBasePlayer_Account = 460,
	CBasePlayer_HasPrimary = 464,
	CBasePlayer_DeathThrowTime = 468,
	CBasePlayer_ThrowDirection = 472,
	CBasePlayer_LastTak = 476,
	CBasePlayer_JustConnected = 480,
	CBasePlayer_ContextHelp = 481,
	CBasePlayer_JoiningState = 484,
	CBasePlayer_IntroCamera = 488,
	CBasePlayer_IntroCamTime = 492,
	CBasePlayer_LastMovement = 496,
	CBasePlayer_MissionBriefing = 500,
	CBasePlayer_TeamChanged = 501,
	CBasePlayer_ModelName = 504,
	CBasePlayer_TeamKills = 508,
	CBasePlayer_IgnoreGlobalChat = 512,
	CBasePlayer_HasNightVision = 516,
	CBasePlayer_NightVisionOn = 517,
	CBasePlayer_RecentPath = 520,
	CBasePlayer_IdleCheckTime = 760,
	CBasePlayer_RadioTime = 764,
	CBasePlayer_RadioMessages = 768,
	CBasePlayer_IgnoreRadio = 772,
	CBasePlayer_HasC4 = 773,
	CBasePlayer_HasDefuser = 774,
	CBasePlayer_KilledByBomb = 775,
	CBasePlayer_BlastVector = 776,
	CBasePlayer_BlastVectorX = 776,
	CBasePlayer_BlastVectorY = 780,
	CBasePlayer_BlastVectorZ = 784,
	CBasePlayer_KilledByGrenade = 788,
	CBasePlayer_MessageQueue = 792,
	CBasePlayer_DisplayHistory = 816,
	CBasePlayer_Menu = 820,
	CBasePlayer_ChaseTarget = 824,
	CBasePlayer_ChaseTargetEnt = 828,
	CBasePlayer_CamSwitch = 832,
	CBasePlayer_Escaped = 836,
	CBasePlayer_IsVIP = 837,
	CBasePlayer_NextRadarUpdate = 840,
	CBasePlayer_LastOrigin = 844,
	CBasePlayer_LastOriginX = 844,
	CBasePlayer_LastOriginY = 848,
	CBasePlayer_LastOriginZ = 852,
	CBasePlayer_CurrentKickVote = 856,
	CBasePlayer_NextVoteTime = 860,
	CBasePlayer_JustKilledTeammate = 864,
	CBasePlayer_HostagesKilled = 868,
	CBasePlayer_MapVote = 872,
	CBasePlayer_CanShoot = 876,
	CBasePlayer_LastFired = 880,
	CBasePlayer_LastAttackedTeammate = 884,
	CBasePlayer_HeadshotKilled = 888,
	CBasePlayer_PunishedForTK = 889,
	CBasePlayer_RecievesNoMoneyNextRound = 890,
	CBasePlayer_TimeCheckAllowed = 892,
	CBasePlayer_HasChangedName = 896,
	CBasePlayer_NewName = 897,
	CBasePlayer_IsDefusing = 929,
	CBasePlayer_HandleSignals = 932,
	CBasePlayer_Signals = 936,
	CBasePlayer_SignalSignal = 936,
	CBasePlayer_SignalState = 940,
	CBasePlayer_CurBombTarget = 944,
	CBasePlayer_PlayerSound = 948,
	CBasePlayer_TargetVolume = 952,
	CBasePlayer_WeaponVolume = 958,
	CBasePlayer_ExtraSoundTypes = 960,
	CBasePlayer_WeaponFlash = 964,
	CBasePlayer_StopExtraSoundTime = 968,
	CBasePlayer_FlashLightTime = 972,
	CBasePlayer_FlashBattery = 976,
	CBasePlayer_ButtonLast = 980,
	CBasePlayer_ButtonPressed = 984,
	CBasePlayer_ButtonReleased = 988,
	CBasePlayer_SndLast = 992,
	CBasePlayer_SndRoomType = 996,
	CBasePlayer_SndRange = 1000,
	CBasePlayer_FallVelocity = 1004,
	CBasePlayer_Items = 1008,
	CBasePlayer_NewAmmo = 1024,
	CBasePlayer_PhysicsFlags = 1028,
	CBasePlayer_NextSuicideTime = 1032,
	CBasePlayer_TimeStepSound = 1036,
	CBasePlayer_TimeWeaponIdle = 1040,
	CBasePlayer_SwimTime = 1044,
	CBasePlayer_DuckTime = 1048,
	CBasePlayer_WallJumpTime = 1052,
	CBasePlayer_SuitUpdate = 1054,
	CBasePlayer_SuitPlayList = 1060,
	CBasePlayer_SuitPlayNext = 1076,
	CBasePlayer_SuitNoRepeat = 1080,
	CBasePlayer_SuitNoRepeatTime = 1208,
	CBasePlayer_LastDamageAmount = 1336,
	CBasePlayer_TBDPrev = 1340,
	CBasePlayer_GeigerRange = 1344,
	CBasePlayer_GeigerDelay = 1348,
	CBasePlayer_GeigerRangePrev = 1352,
	CBasePlayer_StepLeft = 1356,
	CBasePlayer_TextureName = 1360,
	CBasePlayer_TextureType = 1377,
	CBasePlayer_DrownDmg = 1380,
	CBasePlayer_DrownRestored = 1384,
	CBasePlayer_HUDDamageBits = 1388,
	CBasePlayer_InitHUD = 1392,
	CBasePlayer_GameHUDInitialized = 1396,
	CBasePlayer_Train = 1400,
	CBasePlayer_Weapon = 1404,
	CBasePlayer_Tank = 1408,
	CBasePlayer_TankEnt = 1408,
	CBasePlayer_TankSerialNumber = 1412,
	CBasePlayer_DeadTime = 1416,
	CBasePlayer_NoPlayerSound = 1420,
	CBasePlayer_LongJump = 1424,
	CBasePlayer_Sneaking = 1428,
	CBasePlayer_UpdateTime = 1432,
	CBasePlayer_ClientHealth = 1436,
	CBasePlayer_ClientBattery = 1440,
	CBasePlayer_HideHUD = 1444,
	CBasePlayer_ClientHideHUD = 1448,
	CBasePlayer_FOV = 1452,
	CBasePlayer_ClientFOV = 1456,
	CBasePlayer_NumSpawns = 1460,
	CBasePlayer_Observer = 1464,
	CBasePlayer_PlayerItems = 1468,
	CBasePlayer_ActiveItem = 1492,
	CBasePlayer_ClientActiveItem = 1496,
	CBasePlayer_LastItem = 1500,
	CBasePlayer_Ammo = 1504,
	CBasePlayer_AmmoLast = 1632,
	CBasePlayer_AutoAim = 1760,
	CBasePlayer_AutoAimX = 1760,
	CBasePlayer_AutoAimY = 1764,
	CBasePlayer_AutoAimZ = 1768,
	CBasePlayer_OnTarget = 1772,
	CBasePlayer_Deaths = 1776,
	CBasePlayer_SBarState = 1780,
	CBasePlayer_NextSBarUpdateTime = 1796,
	CBasePlayer_StatusBarDisappearDelay = 1800,
	CBasePlayer_SBarString0 = 1928,
	CBasePlayer_LastX = 1932,
	CBasePlayer_LastY = 1936,
	CBasePlayer_CustomSprayFrames = 1940,
	CBasePlayer_NextDecalTime = 1944,
	CBasePlayer_TeamName = 1948,
	CBasePlayer_ModelIndexPlayer = 1964,
	CBasePlayer_AnimExtension = 1968,
	CBasePlayer_GaitSequence = 2000,
	CBasePlayer_GaitFrame = 2004,
	CBasePlayer_GaitYaw = 2008,
	CBasePlayer_PrevGaitOrigin = 2012,
	CBasePlayer_PrevGaitOriginX = 2012,
	CBasePlayer_PrevGaitOriginY = 2016,
	CBasePlayer_PrevGaitOriginZ = 2020,
	CBasePlayer_Pitch = 2024,
	CBasePlayer_Yaw = 2028,
	CBasePlayer_GaitMovement = 2032,
	CBasePlayer_AutoWepSwitch = 2036,
	CBasePlayer_VGUIMenus = 2040,
	CBasePlayer_ShowHints = 2041,
	CBasePlayer_ShieldDrawn = 2042,
	CBasePlayer_OwnsShield = 2043,
	CBasePlayer_WasFollowing = 2044,
	CBasePlayer_NextFollowTime = 2048,
	CBasePlayer_YawModifier = 2052,
	CBasePlayer_BlindUntilTime = 2056,
	CBasePlayer_BlindStartTime = 2060,
	CBasePlayer_BlindHoldTime = 2064,
	CBasePlayer_BlindFadeTime = 2068,
	CBasePlayer_BlindAlpha = 2072,
	CBasePlayer_AllowAutoFollowTime = 2076,
	CBasePlayer_AutoBuyString = 2080,
	CBasePlayer_RebuyString = 2336,
	CBasePlayer_RebuyStruct = 2340,
	CBasePlayer_IsInRebuy = 2380,
	CBasePlayer_LastUpdateTime = 2384,
	CBasePlayer_LastLocation = 2388,
	CBasePlayer_ProgressStart = 2420,
	CBasePlayer_ProgressEnd = 2424,
	CBasePlayer_ObserverAutoDirector = 2428,
	CBasePlayer_CanSwitchObserverModes = 2429,
	CBasePlayer_HeartBeatTime = 2432,
	CBasePlayer_IntenseTimestamp = 2436,
	CBasePlayer_SilentTimestamp = 2440,
	CBasePlayer_MusicState = 2444,
	CBasePlayer_LastCommandTime = 2448,

	CBasePlayerItem_Player = 164,
	CBasePlayerItem_Next = 168,
	CBasePlayerItem_ID = 172,

	CBasePlayerWeapon_PlayEmptySound = 176,
	CBasePlayerWeapon_FireOnEmpty = 180,
	CBasePlayerWeapon_NextPrimaryAttack = 184,
	CBasePlayerWeapon_NextSecondaryAttack = 188,
	CBasePlayerWeapon_TimeWeaponIdle = 192,
	CBasePlayerWeapon_PrimaryAmmoType = 196,
	CBasePlayerWeapon_SecondaryAmmoType = 200,
	CBasePlayerWeapon_Clip = 204,
	CBasePlayerWeapon_ClientClip = 208,
	CBasePlayerWeapon_ClientWeaponState = 212,
	CBasePlayerWeapon_InReload = 216,
	CBasePlayerWeapon_InSpecialReload = 220,
	CBasePlayerWeapon_DefaultAmmo = 224,
	CBasePlayerWeapon_ShellId = 228,
	CBasePlayerWeapon_MaxSpeed = 232,
	CBasePlayerWeapon_DelayFire = 236,
	CBasePlayerWeapon_Direction = 240,
	CBasePlayerWeapon_SecondarySilencerOn = 244,
	CBasePlayerWeapon_Accuracy = 248,
	CBasePlayerWeapon_LastFire = 252,
	CBasePlayerWeapon_ShotsFired = 256,
	CBasePlayerWeapon_Aiming = 260,
	CBasePlayerWeapon_AimingX = 260,
	CBasePlayerWeapon_AimingY = 264,
	CBasePlayerWeapon_AimingZ = 268,
	CBasePlayerWeapon_ModelName = 272,
	CBasePlayerWeapon_Glock18Shoot = 276,
	CBasePlayerWeapon_Glock18ShotsFired = 280,
	CBasePlayerWeapon_FamasShoot = 284,
	CBasePlayerWeapon_FamasShotsFired = 288,
	CBasePlayerWeapon_BurstSpread = 292,
	CBasePlayerWeapon_WeaponState = 296,
	CBasePlayerWeapon_NextReload = 300,
	CBasePlayerWeapon_DecreaseShotsFired = 304,
	CBasePlayerWeapon_FireGlock18 = 308,
	CBasePlayerWeapon_FireFamas = 310,
	CBasePlayerWeapon_PrevPrimaryAttack = 312,
	CBasePlayerWeapon_LastFireTime = 316,

	CWeaponBox_PlayerItems = 136,
	CWeaponBox_AmmoNames = 160,
	CWeaponBox_Ammo = 288,
	CWeaponBox_AmmoTypes = 416,
	CWeaponBox_IsBomb = 420,

	CGrenade_StartDefuse = 384,
	CGrenade_IsC4 = 385,
	CGrenade_BombDefuser = 388,
	CGrenade_BombDefuserEnt = 388,
	CGrenade_BombDefuserSerialKey = 392,
	CGrenade_DefuseCountDown = 396,
	CGrenade_C4Blow = 400,
	CGrenade_NextFreqInterval = 404,
	CGrenade_NextBeep = 408,
	CGrenade_NextFreq = 412,
	CGrenade_BeepName = 416,
	CGrenade_Attenu = 420,
	CGrenade_NextBlink = 424,
	CGrenade_NextDefuse = 428,
	CGrenade_JustBlew = 432,
	CGrenade_Team = 436,
	CGrenade_CurWave = 440,
	CGrenade_CurBombTarget = 444,
	CGrenade_SGSmoke = 448,
	CGrenade_Angle = 452,
	CGrenade_Event = 456,
	CGrenade_LightSmoke = 458,
	CGrenade_Detonated = 459,
	CGrenade_SmokeDetonate = 460,
	CGrenade_SmokeDetonateX = 460,
	CGrenade_SmokeDetonateY = 464,
	CGrenade_SmokeDetonateZ = 468,
	CGrenade_BounceCount = 472,
	CGrenade_RefisteredSound = 476,

	CXM1014_Shell = 320,
	CXM1014_PumpTime = 324,
};

#endif