#pragma once

/*
#define m_flFrameRate 36
#define m_flGroundSpeed	37
#define m_flLastEventCheck	38
#define m_fSequenceFinished	39
#define m_fSequenceLoops 40
#define m_pPlayer 41
#define m_pNext 42
#define m_iId 43
#define m_iPlayEmptySound 44
#define	m_fKnown 44
#define m_fFireOnEmpty 45
#define m_flNextPrimaryAttack 46
#define m_flNextSecondaryAttack	47
#define m_flTimeWeaponIdle 48
#define m_iPrimaryAmmoType 49
#define m_iSecondaryAmmoType 50
#define m_iClip	51
#define m_iClientClip 52
#define m_iClientWeaponState 53
#define m_fInReload	54
#define m_fInSpecialReload 55
#define m_iDefaultAmmo 56
#define m_iShellSpecial 57
#define m_bDelayFire 59
#define m_flAccuracy 62
#define m_iShotsFired 64
#define m_iViewModel 68
#define	b_IsSilent	74
#define m_bSilencerOn 74
#define m_flDecreaseShotsFired 76
#define m_iShell 78
#define m_flPumpTime 79
#define m_flNextAttack 83
#define	flDefusedTime 99
#define	m_flNextBeep 102
#define	m_sBeepName 104
#define	m_flNextBlink 106
#define m_iKevlarType 112
#define m_iPlayerTeam 114
#define m_iAccount 115
#define m_fHasPrimary 116
#define m_iDefaultItems	120
#define m_iJoinedState 121
#define m_pLastCamera 122
#define m_flNextCameraTime 122
//#define m_flNextCameraTime 123
#define m_flLastActivityTime 124
#define m_afButtonLast 245
#define m_afButtonPressed 246
#define m_afButtonReleased 247
#define m_flFallVelocity 251
#define m_iClientHealth 359
#define m_iClientBattery 360
#define m_pActiveItem 373
#define m_modelIndexPlayer 491
#define m_bHasNightVision 516
#define m_bHasC4 773
#define m_bHasDefuser 774
*/